-- USERS
CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    email TEXT UNIQUE,
    password_hash TEXT,
    auth_provider TEXT NOT NULL DEFAULT 'local'
        CHECK (auth_provider IN ('local', 'apple', 'google', 'anonymous')),

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ
);


-- USER DETAILS
CREATE TABLE public.user_details (
    user_id BIGINT PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,

    device_id TEXT,
    platform TEXT CHECK (platform IN ('ios', 'android')),
    locale TEXT,
    timezone TEXT,
    notification_time TIME,
    last_seen_at TIMESTAMPTZ
);


-- GOALS
CREATE TABLE public.goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,

    title TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('do', 'avoid')),
    start_date DATE NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- CHECKINS
CREATE TABLE public.checkins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id BIGINT NOT NULL REFERENCES public.goals(id) ON DELETE CASCADE,

    checkin_date DATE NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('success', 'fail')),

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT checkins_goal_id_checkin_date_key UNIQUE (goal_id, checkin_date)
);


-- SUBSCRIPTIONS
CREATE TABLE public.subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,

    platform TEXT NOT NULL CHECK (platform IN ('ios', 'android')),
    product_id TEXT NOT NULL,
    is_lifetime BOOLEAN NOT NULL DEFAULT false,

    started_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ,

    status TEXT NOT NULL CHECK (status IN ('active', 'expired', 'canceled')),
    original_transaction_id TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- ONLY ONE ACTIVE SUBSCRIPTION PER USER
CREATE UNIQUE INDEX unique_active_subscription
ON public.subscriptions (user_id)
WHERE status = 'active';
